module.exports = class Velominati {
  constructor() {
    this.rules_texts = [
      "Obey The Rules.",
      "Lead by example. It is forbidden for someone familiar with The Rules to knowingly assist another person to breach them.",
      "Guide the uninitiated. No matter how good you think your reason is to knowingly breach The Rules, it is never good enough.",
      "It’s all about the bike. It is, absolutely, without question, unequivocally, about the bike. Anyone who says otherwise is obviously a twatwaffle.",
      "Harden The Fuck Up.",
      "Free your mind and your legs will follow. Your mind is your worst enemy. Do all your thinking before you start riding your bike. Once the pedals start to turn, wrap yourself in the sensations of the ride – the smell of the air, the sound of the tires, the feeling of flight as the bicycle rolls over the road.",
      "Tan lines should be cultivated and kept razor sharp. Under no circumstances should one be rolling up their sleeves or shorts in an effort to somehow diminish one’s tan lines. Sleeveless jerseys are under no circumstances to be employed.",
      "Saddles, bars, and tires shall be carefully matched. 3 valid options are:\n" +
      "Match the saddle to the bars and the tires to black; or\n" +
      "Match the bars to the color of the frame at the top of the head tube and the saddle to the color of the frame at the top of the seat tube and the tires to the color where they come closest to the frame; or\n" +
      "Match the saddle and the bars to the frame decals; or\n" +
      "Black, black, black\n",
      "If you are out riding in bad weather, it means you are a badass. Period. Fair-weather riding is a luxury reserved for Sunday afternoons and wide boulevards. Those who ride in foul weather – be it cold, wet, or inordinately hot – are members of a special club of riders who, on the morning of a big ride, pull back the curtain to check the weather and, upon seeing rain falling from the skies, allow a wry smile to spread across their face. This is a rider who loves the work.",
      "It never gets easier, you just go faster. As this famous quote by Greg LeMan tells us, training, climbing, and racing is hard. It stays hard. To put it another way, per Greg Henderson: “Training is like fighting with a gorilla. You don’t stop when you’re tired. You stop when the gorilla is tired. ” Sur la Plaque, fucktards.",
      "Family does not come first. The bike does. Sean Kelly, being interviewed after the ’84 Amstel Gold Race, spots his wife leaning against his Citroën AX. He interrupts the interview to tell her to get off the paintwork, to which she shrugs, “In your life the car comes first, then the bike, then me. ” Instinctively, he snaps back, “You got the order wrong. The bike comes first.",
      "The correct number of bikes to own is n+1. While the minimum number of bikes one should own is three, the correct number is n+1, where n is the number of bikes currently owned. This equation may also be re-written as s-1, where s is the number of bikes owned that would result in separation from your partner.",
      "If you draw race number 13, turn it upside down. Paradoxically, the same mind that holds such control over the body is also woefully fragile and prone to superstitious thought. It fills easily with doubt and is distracted by ancillary details. This is why the tape must always be perfect, the machine silent, the kit spotless. And, if you draw the unlucky Number 13, turn it upside down to counter-act its negative energy.",
      "Shorts should be black. Team-issue shorts should be black, with the possible exception of side-panels, which may match the rest of the team kit.",
      "Black shorts should also be worn with leader’s jerseys. Black shorts, or at least standard team-kit shorts, must be worn with Championship jerseys and race leadership jerseys. Don’t over-match your kit, or accept that you will look like a douche.",
      "Respect the jersey. Championship and race leader jerseys must only be worn if you’ve won the championship or led the race.",
      "Team kit is for members of the team. Wearing Pro team kit is also questionable if you’re not paid to wear it. If you must fly the colors of Pro teams, all garments should match perfectly, i. e no Mapei jersey with Kelme shorts and Telekom socks.",
      "Know what to wear. Don’t suffer kit confusion. No baggy shorts and jerseys while riding the road bike. No lycra when riding the mountain bike (unless racing XC). Skin suits only for cyclocross.",
      "Introduce Yourself. If you deem it appropriate to join a group of riders who are not part of an open group ride and who are not your mates, it is customary and courteous to announce your presence. Introduce yourself and ask if you may join the group. If you have been passed by a group, wait for an invitation, introduce yourself, or let them go. The silent joiner is viewed as ill-mannered and Anti-V. Conversely, the joiner who can’t shut their cakehole is no better and should be dropped from the group at first opportunity.",
      "There are only three remedies for pain. These are:\n" +
      "If your quads start to burn, shift forward to use your hamstrings and calves, or\n" +
      "If your calves or hamstrings start to burn, shift back to use your quads, or\n" +
      "If you feel wimpy and weak, meditate on Rule #5 and train more!",
      "Cold weather gear is for cold weather. Knickers, vests, arm warmers, shoe covers, and caps beneath your helmet can all make you look like a hardman, when the weather warrants their use. If it isn’t wet or cold, save your Flandrian Best for Flemish weather.",
      "Cycling caps are for cycling. Cycling caps can be worn under helmets, but never when not riding, no matter how hip you think you look. This will render one a douche, and should result in public berating or beating. The only time it is acceptable to wear a cycling cap is while directly engaged in cycling activities and while clad in cycling kit. This includes activities taking place prior to and immediately after the ride such as machine tuning and tire pumping.  Also included are cafe appearances for pre-ride espressi and post-ride pub appearances for body-refueling ales (provided said pub has sunny, outdoor patio – do not stray inside a pub wearing kit or risk being ceremoniously beaten by leather-clad biker chicks). Under these conditions, having your cap skull-side tipped jauntily at a rakish angle is, one might say, de rigueur. All good things must be taken in measure, however, and as such it is critical that we let sanity and good taste prevail: as long as the first sip of the relevant caffeine or hop-based beverage is taken whilst beads of sweat, snow, or rain are still evident on one’s brow then it is legitimate for the cap to be worn. However, once all that remains in the cranial furrows is salt, it is then time to shower, throw on some suitable aprés-ride attire (a woollen Molteni Arcore training top circa ’73 comes to mind) and return to the bar, folded copy of pastel-coloured news publication in hand, ready for formal fluid replacement. It is also helpful if you are a Giant of the Road, as demonstrated here, rather than a giant douchebag.",
      "Tuck only after reaching Escape Velocity. You may only employ the aerodynamic tuck after you have spun out your 53 x 11; the tuck is to be engaged only when your legs can no longer keep up. Your legs make you go fast, and trying to keep your fat ass out of the wind only serves to keep you from slowing down once you reach escape velocity. Thus, the tuck is only to be employed to prevent you slowing down when your legs have wrung the top end out of your block. Tucking prematurely while descending is the antithesis of Casually Deliberate. For more on riding fast downhill see Rule #64 and Rule #85.",
      "Speeds and distances shall be referred to and measured in kilometers. This includes while discussing cycling in the workplace with your non-cycling coworkers, serving to further mystify our sport in the web of their Neanderthalic cognitive capabilities. As the confused expression spreads across their unibrowed faces, casually mention your shaved legs. All of cycling’s monuments are measured in the metric system and as such the English system is forbidden.",
      "The bikes on top of your car should be worth more than the car. Or at least be relatively more expensive. Basically, if you’re putting your Huffy on your Rolls, you’re in trouble, mister. Remember what Sean said.",
      "Make your bike photogenic. When photographing your bike, gussy her up properly for the camera. Some parameters are firm: valve stems at 6 o’clock. Cranks never at 90 or 180 degrees. Others are at your discretion, though the accepted practices include putting the chain on the big cog, and no bidons in the cages.",
      "Shorts and socks should be like Goldilocks. Not too long and not too short. (Disclaimer: despite Sean Yates’ horrible choice in shorts length, he is a quintessential hard man of cycling and is deeply admired by the Velominati. Whereas Armstrong’s short and sock lengths are just plain wrong. ) No socks is a no-no, as are those ankle-length ones that should only be worn by female tennis players.",
      "Socks can be any damn colour you like. White is old school cool. Black is cool too, but were given a bad image by a Texan whose were too long. If you feel you must go colored, make sure they damn well match your kit. Tip: DeFeet Wool-E-Ators rule.",
      "No European Posterior Man-Satchels. Saddle bags have no place on a road bike, and are only acceptable on mountain bikes in extreme cases.",
      "No frame-mounted pumps. Either Co2 cannisters or mini-pumps should be carried in jersey pockets (See Rule #31). The only exception to this rule is to mount a Silca brand frame pump in the rear triangle of the frame, with the rear wheel skewer as the pump mount nob, as demonstrated by members of the 7-Eleven and Ariostea pro cycling teams. As such, a frame pump mounted upside-down and along the left (skewer lever side) seat stay is both old skool and Euro and thus acceptable. We restate at this time that said pump may under no circumstances be a Zefal and must be made by Silca. Said Silca pump must be fitted with a Campagnolo head. It is acceptable to gaffer-tape a mini-pump to your frame when no C02 cannisters are available and your pockets are full of spare kit and energy gels. However, the rider should expect to be stopped and questioned and may be required to empty pockets to prove there is no room in them for the pump.",
      "Spare tubes, multi-tools and repair kits should be stored in jersey pockets. If absolutely necessary, in a converted bidon in a cage on bike. Or, use one of these.",
      "Humps are for camels: no hydration packs. Hydration packs are never to be seen on a road rider’s body. No argument will be entered into on this. For MTB, they are cool.",
      "Shave your guns. Legs are to be carefully shaved at all times. If, for some reason, your legs are to be left hairy, make sure you can dish out plenty of hurt to shaved riders, or be considered a hippie douche on your way to a Critical Mass. Whether you use a straight razor or a Bowie knife, use Baxter to keep them smooth.",
      "Mountain bike shoes and pedals have their place. On a mountain bike.",
      "No visors on the road. Road helmets can be worn on mountain bikes, but never the other way around. If you want shade, see Rule #22.",
      "Eyewear shall be cycling specific. No Aviator shades, blueblockers, or clip-on covers for eye glasses.",
      "The arms of the eyewear shall always be placed over the helmet straps. No exceptions. This is for various reasons that may or may not matter; it’s just the way it is.",
      "Don’t Play Leap Frog. Train Properly: if you get passed by someone, it is nothing personal, just accept that on the day/effort/ride they were stronger than you. If you can’t deal, work harder. But don’t go playing leap frog to get in front only to be taken over again (multiple times) because you can’t keep up the pace. Especially don’t do this just because the person overtaking you is a woman. Seriously. Get over it.",
      "Never ride without your eyewear. You should not make a habit of riding without eyewear, although approved extenuating circumstances include fog, overheating, and lighting condition. When not worn over the eyes, they should be neatly tucked into the vents of your helmet.  If they don’t fit, buy a new helmet. In the meantime you can wear them backwards on the back of your head or carefully tuck them into your jersey pocket, making sure not to scratch them on your tools (see item 31).",
      "Tires are to be mounted with the label centered over the valve stem. Pro mechanics do it because it makes it easier to find the valve. You do this because that’s the way pro mechanics do it. This will save you precious seconds while your fat ass sits on the roadside fumbling with your CO2 after a flat. It also looks better for photo opportunities. Note: This obviously only applies to clinchers as tubulars don’t give you a choice.",
      "Quick-release levers are to be carefully positioned. Quick release angle on the front skewer shall be an upward angle which tightens just aft of the fork and the rear quick release shall tighten at an angle that bisects angle between the seat and chain stays. It is acceptable, however, to have the rear quick release tighten upward, just aft of the seat stay, when the construction of the frame or its dropouts will not allow the preferred positioning. For Time Trial bikes only, quick releases may be in the horizontal position facing towards the rear of the bike. This is for maximum aero effect.",
      "A bike race shall never be preceded with a swim and/or followed by a run. If it’s preceded with a swim and/or followed by a run, it is not called a bike race, it is called duathlon or a triathlon. Neither of which is a bike race. Also keep in mind that one should only swim in order to prevent drowning, and should only run if being chased. And even then, one should only run fast enough to prevent capture.",
      "Don’t be a jackass. But if you absolutely must be a jackass, be a funny jackass. Always remember, we’re all brothers and sisters on the road.",
      "Position matters. In order to find the V-Locus, a rider’s handlebars on their road bike must always be lower than their saddle. The only exception to this is if you’re revolutionizing the sport, in which case you must also be prepared to break the World Hour Record. The minimum allowable tolerance is 4cm; there is no maximum, but people may berate you if they feel you have them too low.",
      "Slam your stem. A maximum stack height of 2cm is allowed below the stem and a single 5mm spacer must always – always – be stacked above. A “slammed down” stack height is preferable; meaning that the stem is positioned directly on the top race of the headset.",
      "Keep your bars level. Handlebars will be mounted parallel to the ground or angled slightly upward. While they may never be pointed down at all, they may be angled up slightly; allowed handlebar tilt is to be between 180 and 175 degrees with respect to the level road. The brake levers will preferably be mounted such that the end of the brake lever is even with the bottom of the bar. Modern bars, however, dictate that this may not always be possible, so tolerances are permitted within reason. Brake hoods should not approach anything near 45 degrees, as some riders with poor taste have been insisting on doing.",
      "Drink Tripels, don’t ride triples. Cycling and beer are so intertwined we may never understand the full relationship. Beer is a recovery drink, an elixir for post-ride trash talking and a just plain excellent thing to pour down the neck. We train to drink so don’t fool around. Drink quality beer from real breweries. If it is brewed with rice instead of malted barley or requires a lime, you are off the path. Know your bittering units like you know your gear length. Life is short, don’t waste it on piss beer.",
      "Saddles must be level and pushed back. The seating area of a saddle is to be visually level, with the base measurement made using a spirit level. Based on subtleties of saddle design and requirements of comfort, the saddle may then be pitched slightly forward or backward to reach a position that offers stability, power, and comfort. If the tilt of the saddle exceeds two degrees, you need to go get one of those saddles with springs and a thick gel pad because you are obviously a big pussy. The midpoint of the saddle as measured from tip to tail shall fall well behind and may not be positioned forward of the line made by extending the seat tube through the top of the saddle. (Also see Rule #44. )",
      "Keep the rubber side down. It is completely unacceptable to intentionally turn one’s steed upside down for any reason under any circumstances. Besides the risk of scratching the saddle, levers and stem, it is unprofessional and a disgrace to your loyal steed. The risk of the bike falling over is increased, wheel removal/replacement is made more difficult and your bidons will leak. The only reason a bicycle should ever be in an upside down position is during mid-rotation while crashing. This Rule also applies to upside down saddle-mount roof bars.",
      "Facial hair is to be carefully regulated. No full beards, no moustaches. Goatees are permitted only if your name starts with “Marco” and ends with “Pantani”, or if your head is intentionally or unintentionally bald. One may never shave on the morning of an important race, as it saps your virility, and you need that to kick ass.",
      "Livestrong wristbands are cockrings for your arms. While we hate cancer, isn’t it better to just donate some money and not have to advertise the fact for the next five years? You may as well get “tryhard wanker” tattooed on your forehead. Or you may well be a bogan.",
      "Drink in Moderation. Bidons are to be small in size. 500-610ml maximum, no extra large vessels are to be seen on one’s machine. Two cages can be mounted, but only one bidon on rides under two hours is to be employed. Said solo bidon must be placed in the downtube cage only. You may only ride with a bidon in the rear cage if you have a front bidon, or you just handed your front bidon to a fan at the roadside and you are too busy crushing everyone to move it forward until you take your next drink. Bidons should match each other and preferably your bike and/or kit. The obvious exception is the classic Coca-Cola bidon which by default matches any bike and/or kit due to its heritage. Coca-Cola should only be consumed flat and near the end of a long ride or all-day solo breakaway on the roads of France.",
      "Keep your kit clean and new. As a courtesy to those around you, your kit should always be freshly laundered, and, under no circumstances should the crackal region of your shorts be worn out or see-through.",
      "No aerobars on road bikes. Aerobars or other clip-on attachments are under no circumstances to be employed on your road bike. The only exception to this is if you are competing in a mountain timetrial.",
      "Earn your turns. If you are riding down a mountain, you must first have ridden up the mountain. It is forbidden to employ powered transportation simply for the cheap thrill of descending. The only exception to this is if you are doing intervals on Alpe d’Huez or the Plan de Corones and you park your car up top before doing 20 repeats of the climb.",
      "Espresso or macchiato only. When wearing cycling kit and enjoying a pre or post ride coffee, it is only appropriate to drink espresso or macchiato. If the word soy/skim latte is heard to be used by a member wearing cycling apparel, then that person must be ceremonially beaten with Co2 canisters or mini pumps by others within the community.",
      "No stickers. Nobody gives a shit what causes you support, what war you’re against, what gear you buy, or what year you rode RAGBRAI.  See Rule #5 and ride your bike. Decals, on the other hand, are not only permissible, but extremely Pro.",
      "Support your local bike shop. Never buy bikes, parts or accessories online. Going into your local shop, asking myriad inane questions, tying up the staff’s time, then going online to buy is akin to sleeping with your best friend’s wife, then having a beer with him after. If you do purchase parts online, be prepared to mount and maintain them yourself. If you enter a shop with parts you have bought online and expect them to fit them, be prepared to be told to see your online seller for fitting and warranty help.",
      "Hold your line. Ride predictably, and don’t make sudden movements. And, under no circumstances, are you to deviate from your line.",
      "Ditch the washer-nut and valve-stem cap. You are not, under any circumstances, to employ the use of the washer-nut and valve-stem cap that come with your inner-tubes or tubulars. They are only supplied to meet shipping regulations. They are useless when it comes to tubes and tires.",
      "Like your guns, saddles should be smooth and hard. Under no circumstances may your saddle have more than 3mm of padding. Special allowances will be made for stage racing when physical pain caused by subcutaneous cysts and the like (“saddle sores”) are present. Under those conditions, up to 5mm of padding will be allowed – it should be noted that this exception is only temporary until the condition has passed or been excised. A hardman would not change their saddle at all but instead cut a hole in it to relieve pressure on the delicate area. It is noted that if Rule #48 and/or Rule #5 is observed then any “padding” is superfluous.",
      "You shall not ride with earphones. Cycling is about getting outside and into the elements and you don’t need to be listening to Queen or Slayer in order to experience that. Immerse yourself in the rhythm and pain, not in whatever 80’s hair band you call “music”.  See Rule #5 and ride your bike.",
      "Point in the direction you’re turning. Signal a left turn by pointing your left arm to the left. To signal a right turn, simply point with your right arm to the right. This one is, presumably, mostly for Americans: that right-turn signal that Americans are taught to make with your left arm elbow-out and your forearm pointing upwards was developed for motor-vehicles prior to the invention of the electric turn signal since it was rather difficult to reach from the driver-side all the way out the passenger-side window to signal a right turn. On a bicycle, however, we don’t have this limitation and it is actually quite easy to point your right arm in the direction you are turning. The American right-turn signal just makes you look like you’re waving “hello” to traffic.",
      "Cornering confidence increases with time and experience. This pattern continues until it falls sharply and suddenly.",
      "Maintain and respect your machine. Bicycles must adhere to the Principle of Silence and as such must be meticulously maintained. It must be cherished, and when leaning it against a wall, must be leaned carefully such that only the bars, saddle, or tires come in contact with the wall or post. This is true even when dismounting prior to collapsing after the World Championship Time Trial. No squeaks, creaks, or chain noise allowed. Only the soothing hum of your tires upon the tarmac and the rhythm of your breathing may be audible when riding. When riding the Pave, the sound of chain slap is acceptable. The Principle of Silence can be extended to say that if you are suffering such that your breathing begins to adversely affect the enjoyment of the other riders in the bunch, you are to summarily sit up and allow yourself to be dropped.",
      "No mirrors. Mirrors are allowed on your (aptly named) Surly Big Dummy or your Surly Long Haul Trucker. Not on your road steed. Not on your Mountain bike. Not on your helmet. If someone familiar with The Rules has sold you such an abomination, return the mirror and demand a refund, plus interest and damages.",
      "Do your time in the wind. Nobody likes a wheel sucker. You might think you’re playing a smart tactical game by letting everyone else do the work while you sit on, but races (even Town Sign Sprints) are won through cooperation and spending time on the rivet, flogging yourself and taking risks. Riding wheels and jumping past at the end is one thing and one thing only: poor sportsmanship.",
      "Rides are to be measured by quality, not quantity. Rides are to be measured by the quality of their distance and never by distance alone. For climbing rides, distances should be referred to by the amount of vertical covered; flat and rolling rides should be referred to by their distance and average speed. For example, declaring “We rode 4km” would assert that 4000m were climbed during the ride, with the distance being irrelevant. Conversely, a flat ride of 150km at 23kmh is not something that should be discussed in an open forum and Rule #5 must be reviewed at once.",
      "Cycling shoes and bicycles are made for riding. Any walking conducted while wearing cycling shoes must be strictly limited. When taking a slash or filling bidons during a 200km ride (at 38kmh, see Rule #68) one is to carefully stow one’s bicycle at the nearest point navigable by bike and walk the remaining distance. It is strictly prohibited that under any circumstances a cyclist should walk up a steep incline, with the obvious exception being when said incline is blocked by riders who crashed because you are on the Koppenberg. For clarification, see Rule #5.",
      "The purpose of competing is to win. End of. Any reference to not achieving this should be referred immediately to Rule #5.",
      "Train Properly. Know how to train properly and stick to your training plan. Ignore other cyclists with whom you are not intentionally riding. The time for being competitive is not during your training rides, but during competition.",
      "Legs speak louder than words. Unless you routinely demonstrate your riding superiority and the smoothness of your Stroke, refrain from discussing your power meter, heartrate, or any other riding data. Also see Rule #74.",
      "Gear and brake cables should be cut to optimum length. Cables should create a perfect arc around the headtube and, whenever possible, cross under the downtube. Right shifter cable should go to the left cable stop and vice versa.",
      "V Meters or small computers only. Forego the data and ride on feel; little compares to the pleasure of riding as hard as your mind will allow. Learn to read your body, meditate on Rule #5, and learn to push yourself to your limit. Power meters, heart rate monitors and GPS are bulky, ugly and superfluous. Any cycle computer, if deemed necessary, should be simple, small, mounted on the stem and wireless.",
      "Race numbers are for races. Remove it from your frame before the next training ride because no matter how cool you think it looks, it does not look cool. Unless you are in a race. In which case it looks cool.",
      "Helmets are to be hung from your stem. When not worn, helmets are to be clipped to the stem and draped over your handlebars thusly.",
      "Respect the earth; don’t litter. Cycling is not an excuse to litter. Do not throw your empty gel packets, energy bar wrappers or punctured tubes on the road or in the bush. Stuff em in your jersey pockets, and repair that tube when you get home.",
      "Remove unnecessary gear. When racing in a criterium of 60 minutes or less the second (unused) water bottle cage must be removed in order to preserve the aesthetic of the racing machine.",
      "Fight for your town lines. Town lines must be contested or at least faked if you’re not in to it or too shagged to do anything but pedal the bike.",
      "Always be Casually Deliberate. Waiting for others pre-ride or at the start line pre-race, you must be tranquilo, resting on your top tube thusly. This may be extended to any time one is aboard the bike, but not riding it, such as at stop lights.",
      "Don’t talk it up. Rides and crashes may only be discussed and recounted in detail when the rider required external assistance in recovery or recuperation. Otherwise refer to Rule #5.",
      "Close the gap. Whilst riding in cold and/or Rule #9 conditions replete with arm warmers, under no circumstances is there to be any exposed skin between the hems of your kit and the hems of your arm warmers. If this occurs, you either need to wear a kit that fits you properly or increase the size of your guns. Arm warmers may, however, be shoved to the wrists in Five and Dime scenarios, particularly those involving Rule #9 conditions. The No-Gap Principle also applies to knee and leg warmers with the variation that these are under no circumstances to be scrunched down around the ankles; Merckx have mercy on whomever is caught in such a sad, sorry state. It is important to note that while one can wear arm warmers without wearing knee or leg warmers, one cannot wear knee or leg warmers without wearing arm warmers (or a long sleeve jersey). It is completely inappropriate to have uncovered arms, while covering the knees, with the exception of brief periods of time when the arm warmers may be shoved to the wrists while going uphill in a Five and Dime situation. If the weather changes and one must remove a layer, the knee/leg coverings must go before the arm coverings. If that means that said rider must take off his knee or leg warmers while racing, then this is a skill he must be accomplished in. The single exception would be before an event in which someone plans on wearing neither arm or leg warmers while racing, but would like to keep the legs warm before the event starts; though wearing a long sleeve jersey over the racing kit at this time is also advised. One must not forget to remove said leg warmers.",
      "Be self-sufficient. Unless you are followed by a team car, you will repair your own punctures. You will do so expediently, employing your own skills, using your own equipment, and without complaining that your expensive tyres are too tight for your puny thumbs to fit over your expensive rim. The fate of a rider who has failed to equip himself pursuant to Rule #31, or who knows not how to use said equipment, shall be determined at the discretion of any accompanying or approaching rider in accordance with Rule #84.",
      "Follow the Code. Consistently with The Code Of The Domestique, the announcement of a flat tyre in a training ride entitles – but does not oblige – all riders then present in the bunch to cease riding without fear of being labelled Pussies. All stopped riders are thereupon entitled – but not obliged – to lend assistance, instruction and/or stringent criticism of the tyre mender’s technique. The duration of a Rule #84 stop is entirely discretionary, but is generally inversely proportional to the duration of the remaining time available for post-ride espresso.",
      "Descend like a Pro. All descents shall be undertaken at speeds commonly regarded as “ludicrous” or “insane” by those less talented. In addition all corners will be traversed in an outside-inside-outside trajectory, with the outer leg extended and the inner leg canted appropriately (but not too far as to replicate a motorcycle racer, for you are not one), to assist in balance and creation of an appealing aesthetic. Brakes are generally not to be employed, but if absolutely necessary, only just prior to the corner. Also see Rule #64.",
      "Don’t half-wheel. Never half-wheel your riding partners; it’s terrible form – it is always the other guy who sets the pace. Unless, of course, you are on the rivet, in which case it’s an excellent intimidation technique.",
      "The Ride Starts on Time. No exceptions. The upside of always leaving on time is considerable. Others will be late exactly once. You signal that the sanctity of this ride, like all rides, is not something with which you should muck. You demonstrate, not with words but with actions, your commitment. As a bonus, you make more time for post-ride espresso. “On Time”, of course, is taken to mean at V past the hour or half hour.",
      "Don’t surge. When rolling onto the front to take your turn in the wind, see Rule #67, do not suddenly lift the pace unless trying to establish a break. The key to maintaining a high average speed is to work with your companions and allow no gaps to form in the line. It is permissible to lift the pace gradually and if this results in people being dropped then they have been ridden off your wheel and are of no use to the bunch anyway. If you are behind someone who jumps on the pedals when they hit the front do not reprimand the offender with cries of ‘Don’t Surge’ unless the offender is a Frenchman named Serge.",
      "Pronounce it Correctly. All races shall be referred to by the name given in its country of origin, and care shall be taken to pronounce the name as well as possible. For Belgian Races, it is preferable to choose the name given in its region of origin, though it is at the speaker’s discretion to use either the Flemish or Wallonian pronunciation. This principle shall also be extended to apply to riders’ names, bicycle and component marquees, and cycling accoutrements.",
      "Never Get Out of the Big Ring. If it gets steeper, just push harder on the pedals. When pressed on the matter, the Apostle Johan Museeuw simply replied, “Yes, why would you slow down?” It is, of course, acceptable to momentarily shift into the inner ring when scaling the 20% ramps of the Kapelmuur.",
      "No Food On Training Rides Under Four Hours. This one also comes from the Apostle, Johan Museeuw, who said to @frank: “Yes, no food on rides under four hours. You need to lose some weight. ” Or, as Fignon put it, sometimes, when we train, we simply have to go out to meet the Man with the Hammer. The exception is, of course, hard rides over two hours and races. Also, if you’re planning on being out for more than four hours, start eating before you get hungry. This also applies to energy drink supplements.",
      "No Sprinting From the HoodsThe only exception is riders whose name starts with Guiseppe and ends with Saronni. See the Goodwood Worlds in 82.",
      "Descents are not for recovery. Recovery Ales are for RecoveryDescents are meant to be as hard and demanding as – and much more dangerous than – the climbs. Climb hard, descend to close a gap or open one. Descents should hurt, not be a time for recovery. Recovery is designated only for the pub and for shit-talking.",
      "Use the correct tool for the job, and use the tool correctly. Bicycle maintenance is an art; tools are designed to serve specific purposes, and it is essential that the Velominatus learns to use each tool properly when working on their loyal machine.",
      "Never lift your bike over your head. Under no circumstances is it acceptable to raise one’s machine above your head. The only exception is when placing it onto a car’s roof-rack."
    ]

    this.rules_titles = [
      "Obey The Rules",
      "Lead by example",
      "Guide the uninitiated",
      "It’s all about the bike",
      "Harden The Fuck Up",
      "Free your mind and your legs will follow",
      "Tan lines should be cultivated and kept razor sharp",
      "Saddles, bars, and tires shall be carefully matched",
      "If you are out riding in bad weather, it means you are a badass",
      "It never gets easier, you just go faster",
      "Family does not come first",
      "The correct number of bikes to own is n+1",
      "If you draw race number 13, turn it upside down",
      "Shorts should be black",
      "Black shorts should also be worn with leader’s jerseys",
      "Respect the jersey",
      "Team kit is for members of the team",
      "Know what to wear",
      "Introduce Yourself",
      "There are only three remedies for pain",
      "Cold weather gear is for cold weather",
      "Cycling caps are for cycling",
      "Tuck only after reaching Escape Velocity",
      "Speeds and distances shall be referred to and measured in kilometers",
      "The bikes on top of your car should be worth more than the car",
      "Make your bike photogenic",
      "Shorts and socks should be like Goldilocks",
      "Socks can be any damn colour you like",
      "No European Posterior Man-Satchels",
      "No frame-mounted pumps",
      "Spare tubes, multi-tools and repair kits should be stored in jersey pockets",
      "Humps are for camels: no hydration packs",
      "Shave your guns",
      "Mountain bike shoes and pedals have their place",
      "No visors on the road",
      "Eyewear shall be cycling specific",
      "The arms of the eyewear shall always be placed over the helmet straps",
      "Don’t Play Leap Frog",
      "Never ride without your eyewear",
      "Tires are to be mounted with the label centered over the valve stem",
      "Quick-release levers are to be carefully positioned",
      "A bike race shall never be preceded with a swim and/or followed by a run",
      "Don’t be a jackass",
      "Position matters",
      "Slam your stem",
      "Keep your bars level",
      "Drink Tripels, don’t ride triples",
      "Saddles must be level and pushed back",
      "Keep the rubber side down",
      "Facial hair is to be carefully regulated",
      "Livestrong wristbands are cockrings for your arms",
      "Drink in Moderation",
      "Keep your kit clean and new",
      "No aerobars on road bikes",
      "Earn your turns",
      "Espresso or macchiato only",
      "No stickers",
      "Support your local bike shop",
      "Hold your line",
      "Ditch the washer-nut and valve-stem cap",
      "Like your guns, saddles should be smooth and hard",
      "You shall not ride with earphones",
      "Point in the direction you’re turning",
      "Cornering confidence increases with time and experience",
      "Maintain and respect your machine",
      "No mirrors",
      "Do your time in the wind",
      "Rides are to be measured by quality, not quantity",
      "Cycling shoes and bicycles are made for riding",
      "The purpose of competing is to win",
      "Train Properly",
      "Legs speak louder than words",
      "Gear and brake cables should be cut to optimum length",
      "V Meters or small computers only",
      "Race numbers are for races",
      "Helmets are to be hung from your stem",
      "Respect the earth; don’t litter",
      "Remove unnecessary gear",
      "Fight for your town lines",
      "Always be Casually Deliberate",
      "Don’t talk it up",
      "Close the gap",
      "Be self-sufficient",
      "Follow the Code",
      "Descend like a Pro",
      "Don’t half-wheel",
      "The Ride Starts on Time",
      "Don’t surge",
      "Pronounce it Correctly",
      "Never Get Out of the Big Ring",
      "No Food On Training Rides Under Four Hours",
      "No Sprinting From the Hoods",
      "Descents are not for recovery",
      "Use the correct tool for the job, and use the tool correctly",
      "Never lift your bike over your head"
    ]
  }

  get rules() {
    if (this.rules_) {
      return this.rules_
    } else {
      const rulesTemp = this.extract_rule_hash()
      this.rules_ = rulesTemp
      return this.rules_
    }
  }

  extract_rule_hash() {
    return this.rules_texts.map((rule, i) => {
      return {
        rule: {
          index: i + 1,
          title: this.rules_titles[i],
          text: rule,
          source: 'https://www.velominati.com/#the-rules'
        }
      }
    })
  }

  rule(ruleId) {
    const number = parseInt(ruleId)
    return this.rules[number - 1]
  }
}